### ISSUE TITLE
ajax 500 retrieving change history

### ISSUE THREAD

**Issue by nigel-bmlt** [bmlt-enabled/bmlt-root-server#806]
Following a successful PATCH call, attempt to read the change history from web UI dumps (raw from browser network panel):

```
<!DOCTYPE html>
<html lang="en" class="auto">
<!--
Spatie\LaravelIgnition\Exceptions\ViewException: Undefined array key &quot;details&quot; in file /var/www/html/main_server/legacy/local_server/server_admin/c_comdef_admin_ajax_handler.class.php on line 1052

#0 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\Foundation\Bootstrap\HandleExceptions-&gt;handleError()
#1 /var/www/html/main_server/legacy/local_server/server_admin/c_comdef_admin_ajax_handler.class.php(1052): Illuminate\Foundation\Bootstrap\HandleExceptions-&gt;Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/html/main_server/legacy/local_server/server_admin/c_comdef_admin_ajax_handler.class.php(93): c_comdef_admin_ajax_handler-&gt;GetMeetingHistory()
#3 /var/www/html/main_server/legacy/local_server/server_admin/c_comdef_admin_ajax_handler.class.php(1522): c_comdef_admin_ajax_handler-&gt;parse_ajax_call()
#4 /var/www/html/main_server/legacy/local_server/index.php(43): require_once('...')
#5 /var/www/html/main_server/legacy/index.php(21): include('...')
#6 /var/www/html/main_server/resources/views/legacy.blade.php(1): require_once('...')
#7 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')
#8 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#9 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem-&gt;getRequire()
#10 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine-&gt;evaluatePath()
#11 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\View\Engines\CompilerEngine-&gt;get()
#12 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View-&gt;getContents()
#13 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View-&gt;renderContents()
#14 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\View\View-&gt;render()
#15 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response-&gt;setContent()
#16 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\Http\Response-&gt;__construct()
#17 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\Routing\ResponseFactory-&gt;make()
#18 /var/www/html/main_server/app/Http/Controllers/CatchAllController.php(54): Illuminate\Routing\ResponseFactory-&gt;view()
#19 /var/www/html/main_server/app/Http/Controllers/CatchAllController.php(34): App\Http\Controllers\CatchAllController::legacyResponse()
#20 /var/www/html/main_server/app/Http/Controllers/Legacy/LegacyAuthController.php(62): App\Http\Controllers\CatchAllController::handle()
#21 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Legacy\LegacyAuthController-&gt;handle()
#22 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller-&gt;callAction()
#23 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher-&gt;dispatch()
#24 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route-&gt;runController()
#25 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route-&gt;run()
#26 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}()
#27 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#28 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle()
#29 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(59): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#30 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\AuthenticateSession-&gt;handle()
#31 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#32 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession-&gt;handleStatefulRequest()
#33 /var/www/html/main_server/app/Http/Middleware/StartSession.php(23): Illuminate\Session\Middleware\StartSession-&gt;handle()
#34 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\StartSession-&gt;handle()
#35 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#36 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle()
#37 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#38 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle()
#39 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#40 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline-&gt;then()
#41 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router-&gt;runRouteWithinStack()
#42 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router-&gt;runRoute()
#43 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router-&gt;dispatchToRoute()
#44 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\Routing\Router-&gt;dispatch()
#45 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}()
#46 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#47 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#48 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle()
#49 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#50 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#51 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle()
#52 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#53 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle()
#54 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#55 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle()
#56 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#57 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors-&gt;handle()
#58 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#59 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies-&gt;handle()
#60 /var/www/html/main_server/app/Http/Middleware/DatabaseMigrations.php(46): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#61 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\DatabaseMigrations-&gt;handle()
#62 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#63 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline-&gt;then()
#64 /var/www/html/main_server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter()
#65 /var/www/html/main_server/index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle()
#66 {main}
-->...
```

**Comment by jbraswell** [comment]
Thanks for reporting this issue. Will you share the exact request you're making that produces this error?

**Comment by jbraswell** [comment]
Looks like this happens for PATCH requests where nothing actually changed.

**Comment by jbraswell** [comment]
https://github.com/bmlt-enabled/bmlt-root-server/pull/809 fixes the error that occurs when there is an update where no fields are actually changed. If, in your particular case, something did actually change, let me know and we'll figure that out too.

**Comment by jbraswell** [comment]
It would be a good idea to change your code to use `client_interface/?switcher=GetChanges&meeting_id={id}`, because this old api endpoint is going away as soon as the new UI is finished.
