### ISSUE TITLE
3.0.5 error

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bmlt-root-server#903]
```
[previous exception] [object] (Error(code: 0): Undefined constant \"_USER_LEVEL_DISABLED\" at /home/nernaorg/public_html/main_server/legacy/local_server/index.php:92)
[stacktrace]
#0 /home/nernaorg/public_html/main_server/legacy/index.php(21): include()
#1 /home/nernaorg/public_html/main_server/storage/framework/views/0e47d5b322c65bb1ba07e3a56cee803f65e88083.php(1): require_once('/home/nernaorg/...')
#2 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('/home/nernaorg/...')
#3 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#4 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#5 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#6 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/View/View.php(152): Illuminate\\View\\Engines\\CompilerEngine->get()
#7 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/View/View.php(135): Illuminate\\View\\View->getContents()
#8 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/View/View.php(104): Illuminate\\View\\View->renderContents()
#9 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#10 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#11 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()
#12 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()
#13 /home/nernaorg/public_html/main_server/app/Http/Controllers/CatchAllController.php(82): Illuminate\\Routing\\ResponseFactory->view()
#14 /home/nernaorg/public_html/main_server/app/Http/Controllers/CatchAllController.php(47): App\\Http\\Controllers\\CatchAllController::legacyResponse()
#15 /home/nernaorg/public_html/main_server/app/Http/Controllers/Legacy/LegacyAuthController.php(62): App\\Http\\Controllers\\CatchAllController::handle()
#16 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Legacy\\LegacyAuthController->handle()
#17 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#18 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#19 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#20 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#21 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#22 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
```

**Comment by pjaudiomv** [comment]
idk whats up with that error but i think the bigger problem is migration is failing

```
[2023-06-03 18:45:47] production.ERROR: c_comdef_dbsingleton::preparedQuery() SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nernaorg_bmlt.na_comdef_format_types' doesn't exist (View: /home/nernaorg/public_html/main_server/resources/views/legacy.blade.php) {"userId":2,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): c_comdef_dbsingleton::preparedQuery() SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nernaorg_bmlt.na_comdef_format_types' doesn't exist (View: /home/nernaorg/public_html/main_server/resources/views/legacy.blade.php) at /home/nernaorg/public_html/main_server/legacy/server/classes/c_comdef_dbsingleton.class.php:257)
[stacktrace]
#0 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()
#1 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#2 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/View/View.php(152): Illuminate\\View\\Engines\\CompilerEngine->get()
#3 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/View/View.php(135): Illuminate\\View\\View->getContents()
#4 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/View/View.php(104): Illuminate\\View\\View->renderContents()
#5 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#6 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#7 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()
#8 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()
#9 /home/nernaorg/public_html/main_server/app/Http/Controllers/CatchAllController.php(82): Illuminate\\Routing\\ResponseFactory->view()
#10 /home/nernaorg/public_html/main_server/app/Http/Controllers/CatchAllController.php(47): App\\Http\\Controllers\\CatchAllController::legacyResponse()
#11 /home/nernaorg/public_html/main_server/app/Http/Controllers/Legacy/LegacyAuthController.php(62): App\\Http\\Controllers\\CatchAllController::handle()
#12 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Legacy\\LegacyAuthController->handle()
#13 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#14 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#15 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#16 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#17 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#18 /home/nernaorg/public_html/main_server/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
```

**Comment by otrok7** [comment]
Maybe the two issues are related?  Because the first seems to be referencing an old version of a file, and the second seems to be, that a new file isn't even there.

**Comment by pjaudiomv** [comment]
resolved by https://github.com/bmlt-enabled/bmlt-root-server/pull/905
